[project]
name = "qyvo-ai Backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "langchain>=0.3.27",
    "langchain-ollama>=0.3.7",
    "langgraph>=0.6.6",
    "pyinstaller>=6.15.0",
    "python-dotenv>=1.1.1",
]
