export const WIN_MINIMIZE_CHANNEL = 'window:minimize'
export const WIN_MAXIMIZE_CHANNEL = 'window:maximize'
export const WIN_CLOSE_CHANNEL = 'window:close'
export const WIN_ALLOW_MOUSE_PASS_THROUGH = 'window:pass-through'
export const WIN_CURRENT_WIN_ICON = 'window:current-window-icon'
