// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Vite
// plugin that tells the Electron app where to look for the Vite-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_VITE_DEV_SERVER_URL: string
declare const MAIN_WINDOW_VITE_NAME: string

// Preload types
interface ThemeModeContext {
  toggle: () => Promise<boolean>
  dark: () => Promise<void>
  light: () => Promise<void>
  system: () => Promise<boolean>
  current: () => Promise<'dark' | 'light' | 'system'>
}

export interface ElectronWindow {
  minimize: () => Promise<void>
  maximize: () => Promise<void>
  close: () => Promise<void>
  passthrough: (e: boolean) => Promise<boolean>
  getCurrentIcon: () => Promise<string>
}

export interface ChatAgent {
  send: (e: string) => Promise<void>
  read: () => Promise<string[]>
}

declare interface Window {
  themeMode: ThemeModeContext
  electronWindow: ElectronWindow
  chatAgent: ChatAgent
}
